import {
    GET_INGREDIENTS_REQUEST,
    GET_INGREDIENTS_SUCCESS,
    GET_INGREDIENTS_FAILED,
    SET_CURRENT_TAB,
    SET_CURRENT_INGREDIENT,
    GET_ORDER_REQUEST,
    GET_ORDER_SUCCESS,
    GET_ORDER_FAILED,
    BURGER_CLEAR,
    BURGER_SET_BUN,
    BURGER_REMOVE_BUN,
    BURGER_ADD_INGREDIENT,
    BURGER_REMOVE_INGREDIENT,
    BURGER_REPLACE_INGREDIENTS,
    CLEAR_ERRORS,
    USER_REQUEST_SENT,
    USER_REQUEST_FAILED,
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT_USER,
    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAILED,
    SET_USER_INFO_REQUEST,
    SET_USER_INFO_SUCCESS,
    SET_USER_INFO_FAILED,
    REGISTER_REQUEST,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_SUCCESS,
    FORGOT_PASSWORD_FAILED,
    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAILED,
} from '../action-types';

export const ACTION_TYPES = {

    GET_INGREDIENTS_REQUEST: GET_INGREDIENTS_REQUEST,
    GET_INGREDIENTS_SUCCESS: GET_INGREDIENTS_SUCCESS,
    GET_INGREDIENTS_FAILED: GET_INGREDIENTS_FAILED,
  
    SET_CURRENT_TAB: SET_CURRENT_TAB,
    SET_CURRENT_INGREDIENT: SET_CURRENT_INGREDIENT,
  
    GET_ORDER_REQUEST: GET_ORDER_REQUEST,
    GET_ORDER_SUCCESS: GET_ORDER_SUCCESS,
    GET_ORDER_FAILED: GET_ORDER_FAILED,
  
    BURGER_CLEAR: BURGER_CLEAR,
    BURGER_SET_BUN: BURGER_SET_BUN,
    BURGER_REMOVE_BUN: BURGER_REMOVE_BUN,
    BURGER_ADD_INGREDIENT: BURGER_ADD_INGREDIENT,
    BURGER_REMOVE_INGREDIENT: BURGER_REMOVE_INGREDIENT,
    BURGER_REPLACE_INGREDIENTS: BURGER_REPLACE_INGREDIENTS,

    CLEAR_ERRORS: CLEAR_ERRORS,

    USER_REQUEST_SENT: USER_REQUEST_SENT,
    USER_REQUEST_FAILED: USER_REQUEST_FAILED,

    LOGIN_REQUEST: LOGIN_REQUEST,
    LOGIN_SUCCESS: LOGIN_SUCCESS,
    LOGIN_FAILED: LOGIN_FAILED,

    LOGOUT_USER: LOGOUT_USER,

    GET_USER_INFO_REQUEST: GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS: GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAILED: GET_USER_INFO_FAILED,

    SET_USER_INFO_REQUEST: SET_USER_INFO_REQUEST,
    SET_USER_INFO_SUCCESS: SET_USER_INFO_SUCCESS,
    SET_USER_INFO_FAILED: SET_USER_INFO_FAILED,

    REGISTER_REQUEST: REGISTER_REQUEST,
    REGISTER_SUCCESS: REGISTER_SUCCESS,
    REGISTER_FAILED: REGISTER_FAILED,

    FORGOT_PASSWORD_REQUEST: FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_SUCCESS: FORGOT_PASSWORD_SUCCESS,
    FORGOT_PASSWORD_FAILED: FORGOT_PASSWORD_FAILED,
    
    RESET_PASSWORD_REQUEST: RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_SUCCESS: RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAILED: RESET_PASSWORD_FAILED,
    
};
