
export const ACTION_TYPES = {

    GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS",
    GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
    GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED",
  
    SET_CURRENT_TAB: "SET_CURRENT_TAB",
    SET_CURRENT_INGREDIENT: "SET_CURRENT_INGREDIENT",
  
    GET_ORDER_REQUEST: "GET_ORDER",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILED: "GET_ORDER_FAILED",
  
    //BURGER_SET_INGREDIENTS: "BURGER_SET_INGREDIENTS",
    BURGER_CLEAR: "BURGER_CLEAR",
    BURGER_SET_BUN: "BURGER_SET_BUN",
    BURGER_REMOVE_BUN: "BURGER_REMOVE_BUN",
    BURGER_ADD_INGREDIENT: "BURGER_ADD_INGREDIENT",
    BURGER_REMOVE_INGREDIENT: "BURGER_REMOVE_INGREDIENT",
    BURGER_REPLACE_INGREDIENTS: "BURGER_REPLACE_INGREDIENTS",

    CLEAR_ERRORS: "CLEAR_ERRORS",
};
