
export const USER_REQUEST_SENT: "USER_REQUEST_SENT" = "USER_REQUEST_SENT";
export const USER_REQUEST_FAILED: "USER_REQUEST_FAILED" = "USER_REQUEST_FAILED";

export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILED: "LOGIN_FAILED" = "LOGIN_FAILED";

export const LOGOUT_USER: "LOGOUT_USER" = "LOGOUT_USER";

export const GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST" = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS: "USER_INFO_SUCCESS" = "USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED: "USER_INFO_FAILED" = "USER_INFO_FAILED";

export const SET_USER_INFO_REQUEST: "SET_USER_INFO_REQUEST" = "SET_USER_INFO_REQUEST";
export const SET_USER_INFO_SUCCESS: "SET_USER_INFO_SUCCESS" = "SET_USER_INFO_SUCCESS";
export const SET_USER_INFO_FAILED: "SET_USER_INFO_FAILED" = "SET_USER_INFO_FAILED";

export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";

export const FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST" = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" = "FORGOT_PASSWORD_FAILED";

export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";