export const BURGER_CLEAR: "BURGER_CLEAR" = "BURGER_CLEAR";
export const BURGER_SET_BUN: "BURGER_SET_BUN" = "BURGER_SET_BUN";
export const BURGER_REMOVE_BUN: "BURGER_REMOVE_BUN" = "BURGER_REMOVE_BUN";
export const BURGER_ADD_INGREDIENT: "BURGER_ADD_INGREDIENT" = "BURGER_ADD_INGREDIENT";
export const BURGER_REMOVE_INGREDIENT: "BURGER_REMOVE_INGREDIENT" = "BURGER_REMOVE_INGREDIENT";
export const BURGER_REPLACE_INGREDIENTS: "BURGER_REPLACE_INGREDIENTS" = "BURGER_REPLACE_INGREDIENTS";