export const GET_ORDER_REQUEST: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";

export const CLEAR_ERRORS: "CLEAR_ERRORS" = "CLEAR_ERRORS";