export const WS_CONNECTION_PUBLIC_INIT: 'WS_CONNECTION_PUBLIC_INIT' = 'WS_CONNECTION_PUBLIC_INIT';
export const WS_CONNECTION_PRIVATE_INIT: 'WS_CONNECTION_PRIVATE_INIT' = 'WS_CONNECTION_PRIVATE_INIT';

export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_FAILED: 'WS_CONNECTION_FAILED' = 'WS_CONNECTION_FAILED';

export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';

export const WS_GET_ALL_ORDERS: 'WS_GET_ALL_ORDERS' = 'WS_GET_ALL_ORDERS';
export const WS_GET_USER_ORDERS: 'WS_GET_USER_ORDERS' = 'WS_GET_USER_ORDERS';

export const WS_SET_CURRENT_ORDER: 'WS_SET_CURRENT_ORDER' = 'WS_SET_CURRENT_ORDER';

